### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/universal_time_control#2]
I tested with Mindustry, it has worked with it before, but now doesn't seem to work at all. 
https://drive.google.com/file/d/1xNE6oL5sQ7VRje-o8k0RxLj8Yerxj81m/view?usp=sharing

**Comment by jnewman314** [comment]
Please confirm:

* Whether a red bar is shown to the left of the control in UTC when active (toggled on/being held)
* Whether anything interesting is printed to the CMD window

**Comment by darklordabc** [comment]
Yes red bar appears, nothing happens in cmd window just keeps repeating “Process monitor thread loop”

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by darklordabc** [comment]
Not working, tested on doom eternal did not work. Tested with cheat engine and speed hack does work with it.
